---
name: "Unofficial Home Assistant Apps (Add-ons) Repository Updater"
description: Tool for updating Home Assistant App (Add-on) repositories.
author: frenck

branding:
  color: red
  icon: thumbs-up

inputs:
  token:
    description: GitHub token that is allowed to write/commit to the target repo
    required: true
  repository:
    description: The app (add-on) repository to update (e.g., homeassistant-apps/repository)
    required: false
  addon:
    description: Slug of the app (add-on) to update the repository for
    required: false
  force:
    description: Force repository update, even if no changes are detected
    default: "false"
    required: false

runs:
  using: "docker"
  image: "action/Dockerfile"
